version: '3.8'
services:
    client:
        build:
            context: ./client
        ports:
            - "4200:4200"
        container_name: client
        depends_on:
            [api, webapi]

    api:
        restart: always
        build: 
            context: ./nodeapi
        ports:
            - "5000:5000"
        container_name: api
        depends_on:
            [emongodb]

    webapi:
        restart: always
        build: 
            context: ./javaapi
        ports:
            - "9000:9000"
        container_name: webapi
        depends_on:
            [emysqldb]
    
    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        command: ["nginx", "-g", "daemon off;"]
        depends_on:
            [client]

    emongodb:
        image: mongo:4
        container_name: emongodb
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: epoc
    
    emysqldb:
        image: mysql:5.7
        container_name: emysqldb
        restart: always
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: emysqldbpass
          MYSQL_DATABASE: books
          
          